import { DEFAULT_SETTINGS, type UserSettings } from "../lib/types";

export const DEFAULT_USER_SETTINGS: UserSettings = DEFAULT_SETTINGS;

const BASE_LANGUAGE_OPTIONS = {
  tier: "common-200",
  supportsPunctuation: true,
  supportsNumbers: true,
} as const;

export const DEFAULT_LANGUAGES = [
  { code: "en", name: "English", variant: "English", ...BASE_LANGUAGE_OPTIONS },
  { code: "en-1k", name: "English", variant: "English 1k", tier: "1k", supportsPunctuation: true, supportsNumbers: true },
  { code: "es", name: "Spanish", variant: "Espanol", ...BASE_LANGUAGE_OPTIONS },
  { code: "fr", name: "French", variant: "Francais", ...BASE_LANGUAGE_OPTIONS },
  { code: "de", name: "German", variant: "Deutsch", ...BASE_LANGUAGE_OPTIONS },
  { code: "it", name: "Italian", variant: "Italiano", ...BASE_LANGUAGE_OPTIONS },
  { code: "pt-br", name: "Portuguese", variant: "Portugues (Brasil)", ...BASE_LANGUAGE_OPTIONS },
  { code: "pt-pt", name: "Portuguese", variant: "Portugues (Portugal)", ...BASE_LANGUAGE_OPTIONS },
  { code: "nl", name: "Dutch", variant: "Nederlands", ...BASE_LANGUAGE_OPTIONS },
  { code: "sv", name: "Swedish", variant: "Svenska", ...BASE_LANGUAGE_OPTIONS },
  { code: "no", name: "Norwegian", variant: "Norsk", ...BASE_LANGUAGE_OPTIONS },
  { code: "da", name: "Danish", variant: "Dansk", ...BASE_LANGUAGE_OPTIONS },
  { code: "fi", name: "Finnish", variant: "Suomi", ...BASE_LANGUAGE_OPTIONS },
  { code: "pl", name: "Polish", variant: "Polski", ...BASE_LANGUAGE_OPTIONS },
  { code: "cs", name: "Czech", variant: "Cestina", ...BASE_LANGUAGE_OPTIONS },
  { code: "sk", name: "Slovak", variant: "Slovencina", ...BASE_LANGUAGE_OPTIONS },
  { code: "hu", name: "Hungarian", variant: "Magyar", ...BASE_LANGUAGE_OPTIONS },
  { code: "ro", name: "Romanian", variant: "Romana", ...BASE_LANGUAGE_OPTIONS },
  { code: "bg", name: "Bulgarian", variant: "Bulgarski", ...BASE_LANGUAGE_OPTIONS },
  { code: "uk", name: "Ukrainian", variant: "Ukrainska", ...BASE_LANGUAGE_OPTIONS },
  { code: "ru", name: "Russian", variant: "Russkiy", ...BASE_LANGUAGE_OPTIONS },
  { code: "el", name: "Greek", variant: "Ellinika", ...BASE_LANGUAGE_OPTIONS },
  { code: "tr", name: "Turkish", variant: "Turkce", ...BASE_LANGUAGE_OPTIONS },
  { code: "ar", name: "Arabic", variant: "Arabic", ...BASE_LANGUAGE_OPTIONS },
  { code: "he", name: "Hebrew", variant: "Hebrew", ...BASE_LANGUAGE_OPTIONS },
  { code: "fa", name: "Persian", variant: "Farsi", ...BASE_LANGUAGE_OPTIONS },
  { code: "ur", name: "Urdu", variant: "Urdu", ...BASE_LANGUAGE_OPTIONS },
  { code: "hi", name: "Hindi", variant: "Hindi", ...BASE_LANGUAGE_OPTIONS },
  { code: "bn", name: "Bengali", variant: "Bangla", ...BASE_LANGUAGE_OPTIONS },
  { code: "pa", name: "Punjabi", variant: "Punjabi", ...BASE_LANGUAGE_OPTIONS },
  { code: "gu", name: "Gujarati", variant: "Gujarati", ...BASE_LANGUAGE_OPTIONS },
  { code: "mr", name: "Marathi", variant: "Marathi", ...BASE_LANGUAGE_OPTIONS },
  { code: "ta", name: "Tamil", variant: "Tamil", ...BASE_LANGUAGE_OPTIONS },
  { code: "te", name: "Telugu", variant: "Telugu", ...BASE_LANGUAGE_OPTIONS },
  { code: "kn", name: "Kannada", variant: "Kannada", ...BASE_LANGUAGE_OPTIONS },
  { code: "ml", name: "Malayalam", variant: "Malayalam", ...BASE_LANGUAGE_OPTIONS },
  { code: "th", name: "Thai", variant: "Thai", ...BASE_LANGUAGE_OPTIONS },
  { code: "vi", name: "Vietnamese", variant: "Tieng Viet", ...BASE_LANGUAGE_OPTIONS },
  { code: "id", name: "Indonesian", variant: "Bahasa Indonesia", ...BASE_LANGUAGE_OPTIONS },
  { code: "ms", name: "Malay", variant: "Bahasa Melayu", ...BASE_LANGUAGE_OPTIONS },
  { code: "tl", name: "Tagalog", variant: "Filipino", ...BASE_LANGUAGE_OPTIONS },
  { code: "sw", name: "Swahili", variant: "Kiswahili", ...BASE_LANGUAGE_OPTIONS },
  { code: "am", name: "Amharic", variant: "Amharic", ...BASE_LANGUAGE_OPTIONS },
  { code: "yo", name: "Yoruba", variant: "Yoruba", ...BASE_LANGUAGE_OPTIONS },
  { code: "ig", name: "Igbo", variant: "Igbo", ...BASE_LANGUAGE_OPTIONS },
  { code: "ha", name: "Hausa", variant: "Hausa", ...BASE_LANGUAGE_OPTIONS },
  { code: "zu", name: "Zulu", variant: "isiZulu", ...BASE_LANGUAGE_OPTIONS },
  { code: "xh", name: "Xhosa", variant: "isiXhosa", ...BASE_LANGUAGE_OPTIONS },
  { code: "ja", name: "Japanese", variant: "Nihongo", supportsPunctuation: false, supportsNumbers: true, tier: "common-200" },
  { code: "ko", name: "Korean", variant: "Hangug-eo", supportsPunctuation: false, supportsNumbers: true, tier: "common-200" },
  { code: "zh-cn", name: "Chinese", variant: "Chinese (Simplified)", supportsPunctuation: false, supportsNumbers: true, tier: "common-200" },
  { code: "zh-tw", name: "Chinese", variant: "Chinese (Traditional)", supportsPunctuation: false, supportsNumbers: true, tier: "common-200" },
];

export const DEFAULT_QUOTES = [
  {
    languageCode: "en",
    text: "Practice as if you are the slowest, perform as if you are the fastest.",
    source: "Gorilla Type",
    difficulty: 2,
  },
  {
    languageCode: "en",
    text: "Typing speed is not magic. It is rhythm, accuracy, and calm repetition.",
    source: "Gorilla Type",
    difficulty: 2,
  },
  {
    languageCode: "en",
    text: "Small consistency beats short motivation every single day.",
    source: "Gorilla Type",
    difficulty: 1,
  },
  {
    languageCode: "es",
    text: "La velocidad llega cuando la precision deja de fallar.",
    source: "Gorilla Type",
    difficulty: 2,
  },
  {
    languageCode: "fr",
    text: "La vitesse vient quand la precision devient une habitude.",
    source: "Gorilla Type",
    difficulty: 2,
  },
];

export const COMMON_WORDS_BY_LANGUAGE: Record<string, string[]> = {
  en: [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "it", "for", "not", "on", "with", "as", "you", "do", "at", "this", "but",
    "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what", "so", "up",
    "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take", "people", "into",
    "year", "your", "good", "some", "could", "them", "see", "other", "than", "then", "now", "look", "only", "come", "its", "over", "think", "also", "back", "after",
  ],
  "en-1k": [
    "time", "people", "work", "life", "world", "school", "state", "family", "student", "group", "country", "problem", "hand", "part", "place", "case", "week", "company", "system", "program",
    "question", "number", "night", "point", "home", "water", "room", "mother", "area", "money", "story", "fact", "month", "lot", "right", "study", "book", "eye", "job", "word",
  ],
  es: ["el", "la", "de", "que", "y", "a", "en", "un", "ser", "se", "no", "haber", "por", "con", "su", "para", "como", "estar", "tener", "le"],
  fr: ["le", "de", "un", "etre", "et", "a", "il", "avoir", "ne", "je", "son", "que", "se", "qui", "ce", "dans", "en", "du", "elle", "au"],
  de: ["der", "die", "und", "in", "den", "von", "zu", "das", "mit", "sich", "des", "auf", "fur", "ist", "im", "dem", "nicht", "ein", "eine", "als"],
  it: ["il", "di", "e", "a", "la", "in", "un", "per", "che", "non", "con", "una", "sono", "si", "come", "piu", "ma", "ho", "ha", "noi"],
  "pt-br": ["de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "com", "nao", "uma", "os", "no", "se", "na", "por", "mais", "as"],
  "pt-pt": ["de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "com", "nao", "uma", "os", "no", "se", "na", "por", "mais", "as"],
  nl: ["de", "het", "een", "en", "van", "ik", "te", "dat", "die", "in", "hij", "niet", "zijn", "is", "was", "op", "aan", "met", "als", "voor"],
  sv: ["och", "det", "att", "i", "en", "jag", "hon", "som", "han", "pa", "den", "med", "var", "sig", "for", "sa", "ar", "till", "de", "inte"],
  no: ["og", "i", "jeg", "det", "at", "en", "et", "som", "pa", "de", "med", "han", "av", "ikke", "ikkje", "der", "sa", "var", "meg", "seg"],
  da: ["og", "i", "jeg", "det", "at", "en", "et", "som", "pa", "de", "med", "han", "af", "for", "ikke", "der", "var", "mig", "sig", "men"],
  fi: ["ja", "on", "se", "ei", "oli", "etta", "kun", "myos", "hän", "tai", "mutta", "jos", "niin", "vain", "joka", "sina", "me", "te", "he", "olla"],
  pl: ["i", "w", "na", "to", "z", "sie", "nie", "jest", "do", "co", "ja", "o", "a", "tak", "ze", "od", "po", "jak", "ale", "byc"],
  cs: ["a", "v", "se", "na", "je", "to", "z", "si", "s", "do", "ze", "k", "jsem", "byl", "byla", "pro", "jako", "ale", "co", "ma"],
  sk: ["a", "v", "sa", "na", "je", "to", "z", "si", "s", "do", "ze", "k", "som", "bol", "bola", "pre", "ako", "ale", "co", "ma"],
  hu: ["es", "a", "az", "hogy", "nem", "egy", "van", "volt", "meg", "de", "ha", "mert", "mint", "en", "te", "mi", "ok", "o", "ez", "azt"],
  ro: ["si", "in", "de", "la", "cu", "un", "o", "nu", "este", "sunt", "pe", "ca", "pentru", "ce", "eu", "tu", "el", "ea", "noi", "voi"],
  bg: ["i", "v", "na", "da", "se", "e", "za", "ot", "to", "s", "kato", "ne", "sam", "si", "go", "po", "sa", "ima", "te", "ni"],
  uk: ["i", "v", "ne", "na", "ya", "vin", "z", "do", "sho", "ce", "za", "ale", "yak", "ty", "my", "vy", "vona", "yogo", "iyi", "buty"],
  ru: ["i", "v", "ne", "na", "ya", "on", "s", "chto", "a", "kak", "eto", "po", "no", "oni", "my", "vy", "ona", "ot", "byt", "dlya"],
  el: ["kai", "to", "na", "se", "den", "einai", "sto", "apo", "me", "gia", "ena", "mia", "otan", "pou", "ego", "esy", "emeis", "aftos", "afti", "otan"],
  tr: ["ve", "bir", "bu", "da", "de", "icin", "ile", "ama", "gibi", "ben", "sen", "o", "biz", "siz", "onlar", "var", "yok", "daha", "cok", "ne"],
  ar: ["ana", "anta", "huwa", "hiya", "nahnu", "antum", "hum", "fi", "min", "ila", "ala", "ma", "la", "naam", "laa", "hadha", "tilka", "mae", "kan", "yakun"],
  he: ["ani", "ata", "hu", "hi", "anachnu", "atem", "hem", "be", "min", "el", "al", "ma", "lo", "ken", "ze", "zot", "im", "aval", "ki", "kol"],
  fa: ["man", "to", "u", "ma", "shoma", "in", "az", "be", "ba", "ke", "baraye", "hast", "nist", "bale", "na", "yek", "do", "khub", "bad", "che"],
  ur: ["main", "tum", "woh", "yeh", "hum", "aap", "hain", "tha", "thi", "mein", "se", "ka", "ki", "ke", "aur", "lekin", "agar", "kyun", "kya", "acha"],
  hi: ["yeh", "hai", "aur", "ke", "mein", "ka", "ko", "se", "par", "ek", "tha", "jo", "nahi", "hain", "unhone", "kar", "gaya", "ho", "to", "liye"],
  bn: ["ami", "tumi", "se", "amra", "tara", "eta", "ota", "e", "o", "theke", "jonno", "kintu", "jodi", "keno", "ki", "valo", "kharap", "ache", "nei", "shob"],
  pa: ["mai", "tu", "oh", "asi", "tusi", "ohna", "eh", "uh", "vich", "to", "naal", "te", "par", "je", "ki", "changga", "manda", "hai", "si", "kar"],
  gu: ["hu", "tu", "te", "ame", "tame", "teo", "aa", "e", "ma", "thi", "mate", "ane", "pan", "jo", "shu", "saru", "kharab", "che", "nathi", "kar"],
  mr: ["mi", "tu", "to", "ti", "apan", "tumhi", "te", "ha", "ti", "madhe", "pasun", "sathi", "ani", "pan", "jar", "kay", "changla", "vait", "aahe", "nahi"],
  ta: ["naan", "nee", "avan", "aval", "nam", "neenga", "avargal", "idhu", "adhu", "il", "irundhu", "kaga", "matrum", "aana", "enna", "nalla", "ketta", "ulladhu", "illai", "sei"],
  te: ["nenu", "nuvvu", "atanu", "ame", "manam", "meeru", "vallu", "idi", "adi", "lo", "nundi", "kosam", "mariyu", "kani", "emi", "manchi", "chedu", "undi", "ledu", "cheyu"],
  kn: ["nanu", "neenu", "avanu", "avalu", "navu", "neevu", "avaru", "idu", "adu", "alli", "inda", "gagi", "mattu", "aadre", "enu", "olleyadu", "ketta", "ide", "illa", "maadu"],
  ml: ["njan", "nee", "avan", "aval", "nammal", "ningal", "avar", "ithu", "athu", "il", "ninnu", "vendi", "um", "pakse", "entha", "nalla", "mosham", "undu", "illa", "cheyyu"],
  th: ["chan", "khun", "khao", "rao", "phuak", "ni", "nan", "thi", "chak", "samrap", "lae", "tae", "tha", "arai", "dee", "mai", "mi", "mai", "tham", "pai"],
  vi: ["toi", "ban", "anh", "chi", "chung", "ho", "nay", "kia", "trong", "tu", "cho", "va", "nhung", "neu", "gi", "tot", "xau", "co", "khong", "lam"],
  id: ["saya", "kamu", "dia", "kami", "kita", "mereka", "ini", "itu", "di", "dari", "untuk", "dan", "tetapi", "jika", "apa", "baik", "buruk", "ada", "tidak", "buat"],
  ms: ["saya", "awak", "dia", "kami", "kita", "mereka", "ini", "itu", "di", "dari", "untuk", "dan", "tetapi", "jika", "apa", "baik", "buruk", "ada", "tidak", "buat"],
  tl: ["ako", "ikaw", "siya", "kami", "tayo", "sila", "ito", "iyan", "sa", "mula", "para", "at", "pero", "kung", "ano", "mabuti", "masama", "may", "wala", "gawa"],
  sw: ["mimi", "wewe", "yeye", "sisi", "nyinyi", "wao", "hii", "ile", "katika", "kutoka", "kwa", "na", "lakini", "kama", "nini", "nzuri", "mbaya", "ipo", "hakuna", "fanya"],
  am: ["ene", "ante", "esu", "esua", "enya", "enante", "enesu", "yeh", "ya", "ke", "be", "le", "egna", "gin", "min", "dehna", "metfo", "all", "yellem", "aderg"],
  yo: ["emi", "iwọ", "oun", "awa", "eyin", "won", "eyi", "yen", "ni", "lati", "fun", "ati", "sugbon", "bi", "kini", "dara", "buru", "wa", "ko", "se"],
  ig: ["m", "gi", "o", "anyi", "unu", "ha", "nke", "ahu", "na", "site", "maka", "ma", "mana", "oburu", "gini", "oma", "ojoo", "di", "adighi", "mee"],
  ha: ["ni", "kai", "shi", "ita", "ku", "su", "wannan", "wancan", "a", "daga", "don", "da", "amma", "idan", "me", "mai", "mara", "akwai", "babu", "yi"],
  zu: ["mina", "wena", "yena", "thina", "nina", "bona", "lena", "lokhu", "kule", "ku", "kusuka", "ukuze", "futhi", "kodwa", "uma", "ini", "kuhle", "kubi", "kukhona", "yenza"],
  xh: ["ndi", "wena", "yena", "thina", "nina", "bona", "le", "lena", "phaya", "ku", "ukusuka", "ukuze", "kwaye", "kodwa", "ukuba", "yintoni", "kulungile", "kubi", "kukho", "yenza"],
  ja: ["わたし", "あなた", "かれ", "かのじょ", "わたしたち", "みんな", "これ", "それ", "あれ", "ここ", "そこ", "あそこ", "です", "ます", "する", "ある", "ない", "よい", "わるい", "とき"],
  ko: ["나", "너", "그", "그녀", "우리", "여러분", "이것", "그것", "저것", "여기", "거기", "저기", "이다", "하다", "있다", "없다", "좋다", "나쁘다", "언제", "무엇"],
  "zh-cn": ["我", "你", "他", "她", "我们", "你们", "他们", "这", "那", "在", "从", "为", "和", "但是", "如果", "什么", "好", "坏", "有", "做"],
  "zh-tw": ["我", "你", "他", "她", "我們", "你們", "他們", "這", "那", "在", "從", "為", "和", "但是", "如果", "什麼", "好", "壞", "有", "做"],
};

export const DEFAULT_NOTIFICATION_TEMPLATES = [
  {
    type: "welcome",
    title: "Welcome to Gorilla Type",
    message: "Start your first test to get ranked on the leaderboard.",
  },
  {
    type: "tip",
    title: "Tip",
    message: "Accuracy first. Speed follows naturally.",
  },
];
